# Generated by Django 5.0.6 on 2024-08-02 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_carousel'),
        ('product', '0005_brand_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area_street',
            field=models.CharField(default='default_area_street', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='building_name',
            field=models.CharField(default='default_building_name', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='default_city', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='near_by',
            field=models.CharField(default='default_near_by', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='default_city', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='default_title', max_length=20),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
