# Generated by Django 5.0.6 on 2024-06-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='online-shopping-background-website-mobile-app_269039-166.jpg', upload_to='product/'),
        ),
    ]
