# Generated by Django 5.0.6 on 2024-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/online-shopping-background-website-mobile-app_269039-166.jpg', upload_to='product/'),
        ),
    ]
