# Generated by Django 5.0.6 on 2024-07-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_table='Product_Category_New', to='product.category'),
        ),
    ]
