# Generated by Django 5.0.6 on 2024-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_order_uuid_411e74_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
